name: 'Monorepo Release Helper'
description: 'A GitHub Action that help you publish monorepo release'
author: 'dengfuping'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  branch:
    description: 'The changelog file branch'
  changelogs:
    description: 'The changelog file path'
  dingding-changelogs:
    description: 'The changelog file path for DingTalk'
  dingding-token:
    description: 'DingTalk token, support multiple token'
  dingding-delay-minute:
    description: 'DingTalk delay time for posting message'
  dingding-message-title:
    description: 'DingTalk message title'
  dingding-message-poster:
    description: 'DingTalk poster url'
  dingding-message-footer:
    description: 'DingTalk message footer'
  dingding-message-prettier:
    description: 'whether to prettier DingTalk message'
  token:
    description: 'Github token'
    default: ${{ github.token }}

runs:
  using: node16
  main: 'dist/index.js'
